name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: miseon920/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: bf1168abb895030a7e98413ef6c64675
          TIMEZONE: Asia/Seoul
